from pathlib import Path

REQUIRED_PATHS = [
    "README.md",
    "AGENTS.md",
    "LICENSE",
    "pyproject.toml",
    ".gitignore",
    ".editorconfig",
    ".github/workflows/ci.yml",
    "inspect-repository/SKILL.md",
    "inspect-repository/references/repository-analysis.md",
    "plan-change/SKILL.md",
    "plan-change/references/planning-guidelines.md",
    "isolate-task/SKILL.md",
    "isolate-task/scripts/create_worktree.py",
    "isolate-task/references/git-isolation.md",
    "implement-change/SKILL.md",
    "implement-change/references/implementation-discipline.md",
    "validate-change/SKILL.md",
    "validate-change/scripts/run_validation.py",
    "validate-change/references/validation-evidence.md",
    "before-after/SKILL.md",
    "before-after/scripts/capture_before_after.py",
    "before-after/references/observable-evidence.md",
    "security-review/SKILL.md",
    "security-review/scripts/scan_diff.py",
    "security-review/references/security-heuristics.md",
    "update-documentation/SKILL.md",
    "update-documentation/references/documentation-scope.md",
    "create-pull-request/SKILL.md",
    "create-pull-request/scripts/open_pull_request.py",
    "create-pull-request/references/pull-request-policy.md",
    "review-pull-request/SKILL.md",
    "review-pull-request/scripts/fetch_pull_request.py",
    "review-pull-request/references/review-standards.md",
    "revise-pull-request/SKILL.md",
    "revise-pull-request/scripts/push_revision.py",
    "revise-pull-request/references/revision-discipline.md",
    "completion-report/SKILL.md",
    "completion-report/scripts/build_report.py",
    "completion-report/references/audit-trail.md",
    "schemas/repository-context.schema.json",
    "schemas/change-plan.schema.json",
    "schemas/workspace-result.schema.json",
    "schemas/implementation-result.schema.json",
    "schemas/validation-report.schema.json",
    "schemas/before-after-report.schema.json",
    "schemas/security-review.schema.json",
    "schemas/documentation-update.schema.json",
    "schemas/pull-request-result.schema.json",
    "schemas/pull-request-review.schema.json",
    "schemas/revision-result.schema.json",
    "schemas/completion-report.schema.json",
    "examples/sample-task.md",
    "tests/test_repository_structure.py",
    "tests/test_skill_metadata.py",
    "tests/test_json_schemas.py",
    "tests/test_create_worktree.py",
]


def test_required_repository_paths_exist() -> None:
    root = Path(__file__).resolve().parents[1]
    missing = [path for path in REQUIRED_PATHS if not (root / path).exists()]
    assert missing == []
